# -*- coding: utf-8 -*-
"""fastapi_websocket.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZ6PW97p-GsFuVvDZy4un-CsVaAUH97k
"""

from fastapi import FastAPI, WebSocket, WebSocketDisconnect

# Create FastAPI app
app = FastAPI()

# WebSocket endpoint
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    WebSocket endpoint that echoes messages back to client
    """
    # Accept the WebSocket connection
    await websocket.accept()

    try:
        # Keep receiving messages until client disconnects
        while True:
            # Receive text message from client
            message = await websocket.receive_text()

            # Echo back with "Server received: " prefix
            response = f"Server received: {message}"
            await websocket.send_text(response)

    except WebSocketDisconnect:
        # Client disconnected
        print("Client disconnected")


# Optional: Root endpoint to check if server is running
@app.get("/")
def read_root():
    return {"message": "WebSocket Echo Server is running. Connect to /ws"}

#test with python
import asyncio
import websockets

async def test():
    """
    Simple Python WebSocket client to test the echo server
    """
    async with websockets.connect("ws://localhost:8000/ws") as websocket:
        # Send message
        await websocket.send("Hello Server")

        # Receive response
        response = await websocket.recv()
        print(response)

# Run the test
asyncio.run(test())